name: build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'examples/**'
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: build
        run: yarn ci:build

      - uses: dorny/test-reporter@v1
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: tests-results
          path: reports/*.json
          reporter: mocha-json

  e2e:
    if: ${{ !startsWith(github.ref_name, 'dependabot') }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup

      - name: e2e
        run: |
          yarn ci:build
          yarn ci:e2e

      - uses: dorny/test-reporter@v1
        if: ${{ (success() || failure()) && github.repository == 'mistic100/Photo-Sphere-Viewer' }}
        with:
          name: e2e-results
          path: reports/*.json
          reporter: mocha-json

  # build-doc:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup
  #       uses: ./.github/workflows/shared/setup

  #     - name: build
  #       run: yarn ci:build-doc
